eureka:
  client:
    serviceUrl:
      defaultZone: http://10.162.3.164:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://localhost/pagamento?serverTimezone=UTC
    username: cartoes
    password: cartoes
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true